//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name : AppData.java
//  @ Date : 2012-5-30
//  @ Author : Eric Guo <gjl@my51c.com>
//
//

package com.synertone.aggregation.utils;

import android.app.Activity;
import android.app.Application;
import android.app.NotificationManager;
import android.content.Context;
import android.graphics.Typeface;

import com.android.volley.RequestQueue;
import com.android.volley.toolbox.Volley;
import com.lidroid.xutils.HttpUtils;
import com.synertone.aggregation.bean.AccountModel;

import java.lang.ref.WeakReference;
import java.util.LinkedList;
import java.util.List;


public class AppData extends Application {
    private static final String TAG = "AppData--------->";
    // mkadd
    public static Context mContext;
    public static Typeface fontXiti;// 表示细体字体
    public static Typeface fontPutu;// 表示常规字体
    public static AccountModel accountModel;
    static private String wokringPath;
    private static AppData mInstance;
    private static NotificationManager nm;

    private LinkedList<Activity> mActivityList = new LinkedList<Activity>();

    private List<WeakReference<Activity>> guideActivityList = new LinkedList<WeakReference<Activity>>();
    private List<Activity> actList;
    public static RequestQueue mRequestQueue;
    public static HttpUtils http;

    /**
     * 单例模式中获取唯一的MyApplication实例
     *
     * @return
     */
    public static AppData getInstance() {
        if (null == mInstance) {
            mInstance = new AppData();
        }
        return mInstance;
    }

    /**
     * 获取Context.
     *
     * @return
     */
    public static Context getContext() {
        return mContext;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        initNetWork();



    }


    private void initNetWork() {
        AppData.mRequestQueue = Volley.newRequestQueue(getApplicationContext());
        http = new HttpUtils();
        http.configTimeout(15000);
        http.configSoTimeout(15000);
        http.configCurrentHttpCacheExpiry(500);
    }

    public void addActivity(WeakReference<Activity> activity) {
        guideActivityList.add(activity);
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
    }
}
